




import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { useState } from "react";

const barlow = Barlow({ subsets: ["latin"], weight: "400" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        {children}
      </body>
    </html>
  );
}
